#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs  = env['ROOTLIBS']
if "TMVA" not in rootlibs: rootlibs.append("TMVA");

mu2e_libs = [ 'mu2e_MCDataProducts',
              'mu2e_Mu2eUtilities' ,
             ]
mainlib = helper.make_mainlib ( [
    'CLHEP',
    rootlibs,
    'cetlib_except',
    'eventntuple'
    ] + mu2e_libs )

# Fixme: split into link lists for each module.
helper.make_plugins( [
    mainlib,
    'cetlib',
    'cetlib_except',
    rootlibs,
    'boost_filesystem',
    ] )

helper.make_dict_and_map( [
        mainlib,
        'Core',
        'cetlib_except',
        'canvas'
    ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
