/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "MyPolyPowerPdf.h"

#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <Riostream.h>
#include <TMath.h>

#include <cmath>

ClassImp(MyPolyPowerPdf);

MyPolyPowerPdf::MyPolyPowerPdf(const char *name, const char *title,
                        RooAbsReal& _obs,
                        RooAbsReal& _mean,
                        RooAbsReal& _sigma,
                        RooAbsReal& _alpha,
                        RooAbsReal& _n)
   : RooAbsPdf(name,title),
   obs("obs","obs",this,_obs),
   mean("mean","mean",this,_mean),
   sigma("sigma","sigma",this,_sigma),
   alpha("alpha","alpha",this,_alpha),
   n("n","n",this,_n)
{
}

MyPolyPowerPdf::MyPolyPowerPdf(MyPolyPowerPdf const &other, const char *name)
   : RooAbsPdf(other,name),
   obs("obs",this,other.obs),
   mean("mean",this,other.mean),
   sigma("sigma",this,other.sigma),
   alpha("alpha",this,other.alpha),
   n("n",this,other.n)
{
}


double MyPolyPowerPdf::evaluate() const
{
   return MyPolyPowerPdf_evaluate(obs, mean, sigma, alpha, n);
}

void MyPolyPowerPdf::doEval(RooFit::EvalContext &ctx) const
{
   std::span<const double> obsSpan = ctx.at(obs);
   std::span<const double> meanSpan = ctx.at(mean);
   std::span<const double> sigmaSpan = ctx.at(sigma);
   std::span<const double> alphaSpan = ctx.at(alpha);
   std::span<const double> nSpan = ctx.at(n);

   std::size_t n = ctx.output().size();
   for (std::size_t i = 0; i < n; ++i) {
      ctx.output()[i] = MyPolyPowerPdf_evaluate(obsSpan.size() > 1 ? obsSpan[i] : obsSpan[0],
                               meanSpan.size() > 1 ? meanSpan[i] : meanSpan[0],
                               sigmaSpan.size() > 1 ? sigmaSpan[i] : sigmaSpan[0],
                               alphaSpan.size() > 1 ? alphaSpan[i] : alphaSpan[0],
                               nSpan.size() > 1 ? nSpan[i] : nSpan[0]);
   }
}
void MyPolyPowerPdf::translate(RooFit::Detail::CodeSquashContext &ctx) const
{
   ctx.addResult(this, ctx.buildCall("MyPolyPowerPdf_evaluate", obs, mean, sigma, alpha, n));
}

Int_t MyPolyPowerPdf::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const
{
  // Register that we handle analytical integration for the observable variable
  if (matchArgs(allVars, analVars, obs)) return 1;
  return 0;
}

Double_t MyPolyPowerPdf::analyticalIntegral(Int_t code, const char* rangeName) const
{
  if (code == 1) {
    Double_t xmin = obs.min(rangeName);
    Double_t xmax = obs.max(rangeName);

    // Calculate the moving absolute transition boundaries
    Double_t b_low  = mean - alpha * sigma;
    Double_t b_high = mean + alpha * sigma;

    Double_t total_integral = 0.0;

    // Local lambda function to integrate the Polynomial core piece
    auto poly_integral = [&](Double_t low, Double_t high) {
        if (low >= high) return 0.0;
        auto int_f = [&](Double_t x) {
            Double_t dx = (x - mean) / sigma;
            return x * (0.5 + 0.5 * alpha * alpha) - (sigma / 6.0) * dx * dx * dx;
        };
        return int_f(high) - int_f(low);
    };

    // Local lambda function to integrate the Power law tail piece
    auto tail_integral = [&](Double_t low, Double_t high) {
        if (low >= high) return 0.0;
        auto int_f = [&](Double_t x) {
            Double_t dx = (x - mean) / sigma;
            if (n == 1.0) return (n / alpha) * pow(alpha, n) * sigma * log(abs(dx));
            return (n / alpha) * pow(alpha, n) * sigma * (pow(abs(dx), 1.0 - n) / (1.0 - n));
        };
        return int_f(high) - int_f(low);
    };

    // Piecewise integration across the 3 structural subregions
    // Region 1: Left Tail
    if (xmin < b_low)  total_integral += tail_integral(xmin, std::min(xmax, b_low));
    // Region 2: Central Core
    if (xmax > b_low && xmin < b_high) total_integral += poly_integral(std::max(xmin, b_low), std::min(xmax, b_high));
    // Region 3: Right Tail
    if (xmax > b_high) total_integral += tail_integral(std::max(xmin, b_high), xmax);

    return total_integral;
  }
  return 0;
}
