/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef MyPolyPowerPdf_h
#define MyPolyPowerPdf_h

#include <RooAbsPdf.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <complex>

class MyPolyPowerPdf : public RooAbsPdf {
public:
   MyPolyPowerPdf() {}
   MyPolyPowerPdf(const char *name, const char *title,        RooAbsReal& _obs,
        RooAbsReal& _mean,
        RooAbsReal& _sigma,
        RooAbsReal& _alpha,
        RooAbsReal& _n);
  MyPolyPowerPdf(MyPolyPowerPdf const &other, const char *name=nullptr);
  TObject* clone(const char *newname) const override { return new MyPolyPowerPdf(*this, newname); }
  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const override;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const override;
protected:

  RooRealProxy obs ;
  RooRealProxy mean ;
  RooRealProxy sigma ;
  RooRealProxy alpha ;
  RooRealProxy n ;

  double evaluate() const override;
  void doEval(RooFit::EvalContext &) const override;
  void translate(RooFit::Detail::CodeSquashContext &ctx) const override;

private:

  ClassDefOverride(MyPolyPowerPdf, 1) // Your description goes here...
};
inline double MyPolyPowerPdf_evaluate(double obs, double mean, double sigma, double alpha, double n)
{
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE

   return abs((obs - mean)/sigma) <= alpha ? 0.5 * (1.0 + alpha * alpha - (obs - mean)*(obs - mean)/(sigma*sigma)) : (n/alpha) * pow(alpha / abs((obs - mean)/sigma), n);
}


#endif // MyPolyPowerPdf_h
